# Use an official base image (change as needed)
FROM node:18-alpine  

# Set working directory
WORKDIR /app  

# Copy package.json and install dependencies
COPY package.json package-lock.json ./
RUN npm install --production  

# Copy the rest of the application
COPY . .  

# Expose a port (change if needed)
EXPOSE 3000  

# Start the application
CMD ["node", "server.js"]
